### ISSUE TITLE
[New Content] Display new notes notification on the Home Feed

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#1070]
Below are the user stories for notifying the user when there are new notes on the Home feed. See also #1069

## Users are alerted when new notes are available 

Given that I am a user of Nos 
When there are new notes available 
Then I want to see a notification near the top of my current feed screen that says 

New Notes Available or # new notes 

Designs - Note these will be updated to lavender buttons
https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5808%3A25966&mode=design&t=sChDwE9vXMj1qlTA-1

## Clicking on the new notes button 

Given that I am a user of nos 
When I click on the new notes button
Then I should see the new notes load and I should be at the top with the latest note.

**Comment by joshuatbrown** [comment]
@setch-l The lavender button looks similar to our current secondary button, though it looks brighter and has a gradient background. I don't think we have anything like that in the app, so do we want to use the existing secondary button or create a new one that's just used here? If we used the existing button, it would look like this:

![Image](https://github.com/user-attachments/assets/c839f40c-3f05-47b3-b02f-f2e3c59fc95d)

If we want to use a new one, my main concern is consistency since this would be only used in the feeds (Home and Profile). Maybe that's OK since this is sort of a new control. It also takes a bit more time to implement a new design, though I think it'll be pretty quick.

**Comment by setch-l** [comment]
@joshuatbrown - Based on your post I'm guessing there is not a single CSS style or equivalent for buttons in the app? The goal is for people to be able to see it. If the current button style pops and is visible we can use it. If it blends in, then lets move to the new button style....

**Comment by joshuatbrown** [comment]
@setch-l I'd say that the current button style does not pop and we should use the new style. We do have the equivalent of CSS style -- it's just that we only have two styles right now and neither is quite what we're looking for. So I can add a third style, or just adapt one of the existing ones to the new design and then all of those style buttons in the app would be updated.

I can create the new style and then post screenshots or just let you test a build where the "secondary" style is updated everywhere.
