### ISSUE TITLE
Cannot share logs

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#1097]
**Describe the bug**
Sharing logs is broken for me and Rabble on staging and the production build.

**To Reproduce**
1. Open the side menu
2. Tap Settings
3. Tap "Share Logs"
4. A blank screen is shown

**Expected behavior**
A share sheet opens and you can send the logs somewhere

**Technical info (please complete the following information):**
 - App Version: 0.1.12 (261) Staging and 0.1.11 (241) Production

**Comment by joshuatbrown** [comment]
@mplorentz @rabble I'm seeing the same issue. When I tap "Share Logs" a second time, it does work. Is that true for you, too?

**Comment by joshuatbrown** [comment]
Also just found that if I leave it for a very long time, like several minutes, _eventually_ the share sheet appears. Perhaps `LogHelper.zipLogs()` is just _very_ slow.

**Comment by joshuatbrown** [comment]
It looks to me like we might have:
1. Large log files that take a while to copy to a temporary directory before being zipped.
2. The file system waiting for writes to finish before reading and copying.

I sent myself a couple log files that were 600 KB and 1 MB. It looked to me like my device had 7 files, so if they're each around 1 MB, that's 7 MB we're copying and then trying to send. I don't know if that much data is useful anyway, so we may want to try sending just the most recent file (or two). We may also consider trying to reduce the size of our logs by limiting what we log. A very large portion of our logs look like these:

```
2024/05/08 20:00:43:705  LOG:DEBUG: websocket is connected: Optional("brb.io")
2024/05/08 20:00:43:706  LOG:DEBUG: websocket error: WSError(type: Starscream.ErrorType.protocolError, message: "masked and rsv data is not currently supported", code: 1002) from: brb.io
2024/05/08 20:00:43:706  LOG:DEBUG: websocket error: WSError(type: Starscream.ErrorType.protocolError, message: "masked and rsv data is not currently supported", code: 1002) from: brb.io
2024/05/08 20:00:43:707  LOG:DEBUG: websocket error: WSError(type: Starscream.ErrorType.protocolError, message: "masked and rsv data is not currently supported", code: 1002) from: brb.io
2024/05/08 20:00:43:707  LOG:DEBUG: websocket error: WSError(type: Starscream.ErrorType.protocolError, message: "masked and rsv data is not currently supported", code: 1002) from: brb.io
```

Still, I don't have an explanation for why it's suddenly so slow. I checked Slack and found some logs from Linda from January, and that zip contained about 7 MB of log files (unzipped) and was 336 KB zipped. It doesn't look like much has changed in the size of our logs.

Another hypothesis is that this is related to SwiftUI waiting for _something_. The logical question, then, is _what_? In Instruments I was able to see a Hang using the Time Profiler. But as soon as I add the View Body or View Properties instrument, the bug is not reproducible. So perhaps the profiler is triggering something in the view that's not being triggered when the app runs on its own.

**Comment by mplorentz** [comment]
> @mplorentz @rabble I'm seeing the same issue. When I tap "Share Logs" a second time, it does work. Is that true for you, too?

yes!

This sounds like a very difficult issue :( If you would like to pair on this tomorrow let me know.

**Comment by joshuatbrown** [comment]
Thanks to @mplorentz's git bisect suggestion, I've determined that this is the first bad commit: https://github.com/planetary-social/nos/commit/d8389138d604c2ea90b24cbf983b8a61e63213b8

I'm not 100% sure what part of that commit is the problem, but I suppose my best guess would be the `pointfreeco/swiftui-navigation` upgrade since this feels like a SwiftUI issue. It looks like our `main` branch is on the latest version, 1.3.0, so downgrading might be our only option. I can give that a try and see what happens.

**Comment by joshuatbrown** [comment]
I've [reported](https://github.com/pointfreeco/swiftui-navigation/issues/150) this as a bug in the `swiftui-navigation` project.

**Comment by joshuatbrown** [comment]
Wow, it [sounds like](https://github.com/pointfreeco/swiftui-navigation/discussions/151#discussioncomment-9392650) this is actually a bug in SwiftUI, not in `swiftui-navigation`. We may want to audit our code and see where we use `sheet(unwrapping:)` and confirm that everything works as expected.
