### ISSUE TITLE
[Bug] Mentions dialogue creates a mess in a post [on a mac]

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1144]
Steps to Reproduce 
1. Open Nos on a mac
2. Create a new post
3. Type @ and use the mentions dialogue to find users 
4. select the user 
5. Publish the post
Issue: The mentions have incorrect formatting. 
Expected: Mentions display as @ username - which is a link out to the users' profile. 

![Image](https://github.com/planetary-social/nos/assets/6765558/828f56ec-6292-4780-a599-9207d6535a26)

**Comment by martindsq** [comment]
@setch-l Its hard to know what happened when you wrote that post, how you mentioned people and what exactly you wrote. I did a lot of tests around that and what I found was:

1. The steps to reproduce are not enough, the normal use case when mentioning people is working fine
2. The image you posted depicts wrong nostr: links with strange - characters and more than one consecutive npub. This indicates that something when wrong when mentioning certain people. We have more than one way to mention someone, pasting an npub or typing @ to open the mention dialog, so my tests combined these two ways.
3. I found that users with an emoji in the name (I set up a test account with an emoji: `npub1d4hqsmyejq3s0cc9sh4dngm2s7xdh4q62yy4wrpp6sfrsepq944qtauzgw` cause problems when mentioning them typing the @ character to open the mention dialog and after selecting them, either directly type something else.
4. Not all users you mentioned had an emoji, but that post did add emojis after mentioning them (I don't know how you input emojis in a Mac, it will be useful to know that)

So, I suspect that something wrong is happening with emojis in general when composing a post. So I propose to **limit the scope of this ticket to**:

- Test if emojis also cause a problem in iOS
- If not, find out what macOS does different
- At least, fix the following use case (because its consistently failing):

1. Open Nos on a mac
2. Create a new post
3. Type @ and use the mentions dialogue to find a user with an emoji at the end. for example: `npub1d4hqsmyejq3s0cc9sh4dngm2s7xdh4q62yy4wrpp6sfrsepq944qtauzgw`
4. select the user
5. Write "hey" or do 3 again (without typing anything else in the middle)
6. Publish the post
Issue: The mentions have incorrect formatting.
Expected: Mentions display as @ username - which is a link out to the users' profile.

**Comment by setch-l** [comment]
Hi @martindsq - Are you testing this on production or in a dev environment? I added the emoji's after doing the link using the mentions. Perhaps there was not a space, so the fix could be to add a space after a mention in a post. However a basic mention using the mentions dialogue doesn't seem to work either. I would try testing on production to see as well.

**Comment by mplorentz** [comment]
I'm not sure adding a space is even enough. Especially if there are emojis in the name it looks like there is whitespace around the mention even when there isn't:

https://github.com/planetary-social/nos/assets/1165004/21f7f0d3-d4a7-4254-998d-349aac8b0770


I think we should write code to detect the nostr links even if the user didn't leave whitespace around them - we know what they look like and what the length should be.

**Comment by mplorentz** [comment]
I am also seeing a lot of weird behavior if you try to go back and type something before the mention. It duplicates the link and this can cause really weird things upon publish. Here are two examples:

https://github.com/planetary-social/nos/assets/1165004/69479c82-23ae-4151-95ae-c1e03722dc3f


https://github.com/planetary-social/nos/assets/1165004/9bbaa01b-a4ab-4441-851c-cd771117e9e3

**Comment by setch-l** [comment]
This is unfortunately not fixed. @mplorentz - let's have you work on this one next sprint to sort it out. 

Steps to reproduce: 
1. Use the mentions dialogue to mention someone. 
2. Insert an emoji before the mention. 
Issue: The mention works, but then the pubid is visibile in the post: 
Example: note1ccne5eaagpkcwrjlhz23wennrc58v4047ttnygne6m80zg7t5rxsufk640

Expected: If I insert emoji's before a mention then the mention works and there's no visible npub address in the post in Nos. 



![Image](https://github.com/planetary-social/nos/assets/6765558/eb56ce5e-95d5-48ed-8b54-97c9d8d207b4)
