### ISSUE TITLE
Refactor the Editor on Nos

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1146]
There are many bugs in the editor on Nos. Most involve the cursor jumping after adding any sort of media file, emoji, etc. 

AC - 
When a user adds any sort of media to the post, the cursor lands just after the added item 
The cursor does not randomly jump around while creating a post. 

Steps to reproduce: 
1. Open nos on a mac or ipad
2. Create a post or reply 
3. Add an image, link or emoji
Issue: the cursor skips to the bottom of the editor. 

Note I am only seeing this on a mac, but Rabble might have also seen this on the phone.

**Comment by mplorentz** [comment]
I wrote up a fix for this but it caused other weird issues that I couldn't fix. I'm going to take a step back and meet with @martindsq tomorrow to figure out a path forward. I think we may need a larger refactoring effort because our system of syncing the typed String between SwiftUI and UIKit is having so many problems.
