### ISSUE TITLE
[Bug] Profile screens only load 3 posts

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1192]
Steps to reproduce: Build 290 or 297 

1. Open Nos on a mac
2. Search for Meredith Whittaker npub15s3hussvmv9nyvw3w8lg0x72udazmdat7tcj5vmmjafnwcvv8tpqzz6r6y
Issue: only her 3 most recent posts load. 

1. Open Nos on a mac
2. Search for We Distribute 
3. Scan their list of profile posts for the one they wrote about Nostr 
Issue: only the three most recent posts load. 
4. Pull to refresh looks like it is doing soemthing but then older posts do not load. 

Expected: If I pull to refresh the page then the app so go grab more posts on the network.

**Comment by mplorentz** [comment]
This bug happens if the user posts 20 replies (or deletes) in a row without publishing a new root note. The problem is that the `PagedRelaySubscription` won't be told to load the next page because no cells were added to the `PagedNoteDataSource` from the previous page when the "Notes" tab is selected on the profile screen. A workaround is to select the "Activity" tab - it pages fine. 

I'm working on a fix.
