### ISSUE TITLE
[Search UI] Improve the search ux

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1242]
Presently the search UI is most performant when the keyboard is active. However when a user presses the search button on the keyboard all the results disappear. 

For this ticket we want to improve the following ux issues

1. When a user types past 4 characters or known results on the device, do not remove the known results from the view. 
2. When a user presses the search button on the keyboard, do not remove the search results and start the spinner, instead keep the results. Continue running the search in the background and show a pill with the following when new results are available: 
Click for new results. Use this design pattern: https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=5976-802&t=JhWjDxsaCzzpqXHA-1
3. Make sure we don't eliminate two character search when a user hits the search button. For example typing "we" > hit search button should display results with "we" in them including "We Distribute", "welcome", etc.

**Comment by joshuatbrown** [comment]
@setch-l I made some simpler changes to the way search works. The changes will appear in a staging build soon (I'd guess build 380 and later) and I'd love to get your thoughts. Since I took the simple approach, there's no pill that appears when new results are available, but I think you'll like this much better than what we had before. We can certainly spend more time on it if what I did isn't sufficient.
