### ISSUE TITLE
[Content Moderation hot fixes] Spam is missing as an option in slack > Updating to NIP56

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1247]
Spam is missing as an option in slack

Steps to reproduce: 
1. Open Nos
2. Flag a note or an account for spam 
3. Send the flag to Nos for review
4. Open slack moderation channel
Issue: Spam is missing as an option in slack so is other. 

It's unclear to me what options exist in slack. Do these match the 1984 kinds? Or something else? 

![Image](https://github.com/planetary-social/nos/assets/6765558/849783f1-6257-498f-90f5-d5b938cb01a2)

**Comment by dcadenas** [comment]
What we display and send to reportinator directly are the [categories](https://platform.openai.com/docs/guides/moderation) used by OpenAI this is later mapped to [nip-69 categories](https://github.com/s3x-jay/nostr-nips/blob/master/69.md). OpenAI doesn't have a Spam category but nip-69 does.

So we'd need to:

- [ ] 1. Change cleanstr to instead create slack messages that point to nip-69 ids
- [ ] 2. Change reportinator to interpret these ids received from the Slack buttons, instead of those from OpenAI.
- [ ] 3. Also change reportinator to produce Slack messages that use nip-69 ids. As a reminder, this is because not only cleanstr creates slack messages, also reportinator does when a request to flag a user is received, which doens't need a pass through Cleanstr for OpenAI processing.

**Comment by setch-l** [comment]
As part of the content moderation hot fixes, we did not simplify the labeling nip we were using. NIP69 labels will be great in the future, but today they are too complicated for what the existing apps and community needs. Instead after speaking with @dcadenas we will map our in-app labels to NIP56 labels and remove the NIP69 from the workflow. This will allow us to have spam in the slack bot moving forward. Below are the list of updates needed to complete this work. 

Updates: 

- [ ] Replace NIP69 references with NIP56
- [ ] Map the Nos content categories to the NIP56 categories as follows: 
Content Labels In App | NIP56 Label 
Spam = Spam 
Nudity or Sexual Content = Nudity
Coarse Language or Intolerance = Profanity
Illegal = Illegal (also encompassed malware) 
Other = Other 

- [ ] Map the Nos User label categories to the NIP56 categories as follows: 
Nos Profile labels | NIP56 Labels 
Spam = Spam
Harassment = Profanity
NSFW = Nudity
Illegal = Illegal 
Other = Other 

- [ ] Add Impersonation to the in-app list for User labels 

- [ ] Slack list of labels should match what we have in the app or NIP56 (if what we have in the app is too hard).

**Comment by mplorentz** [comment]
@setch-l telling the user they are publishing a public flag for harassment and then under-the-hood publishing an event that labels it as "profanity" seems really user-hostile. I would be pretty mad if an app I was using did that. If you want to stick with the NIP-56 categories then I really think we should also update our UI to match what we are actually going to publish on the user's behalf.

**Comment by setch-l** [comment]
We have a plan to submit a nip update to change the language for profanity to coarse language or intolerance to match what is in our app and that better reflects the spirit of the profanity label. 

In general all of this is much more complicated than it needs to be given the functionality we offer users today. Daniel and I are simplifying what exists now so we can build upon easily in the future. Today we need to navigate between 2 nips & open AI. It’s a lot of extra code that was causing confusion for users.
