### ISSUE TITLE
[Following List] Update to newer bio cards

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1269]
Given that I am user of Nos
When I click on the list of people someone is following 
Then I should see the new bio cards (used on the Discover tab) that include: 
- profile image
- bio
- Followed by info 

Note this story is based on feedback from new users who are having issues Discovering people to follow.

**Comment by joshuatbrown** [comment]
@setch-l I'm also updating the mute list card design very slightly since it was shared with the old follow card. Now that it's only used by the muted users list, it can be a little more streamlined (and not have the Follow button). See [the PR description](https://github.com/planetary-social/nos/pull/1363) for a side-by-side comparison of both the updated following list and the updated mute list, as well as testing steps.
