### ISSUE TITLE
[Design] Redesign the post to relay experience

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1367]
Overview
Today it is not clear that users have the option to post to a single relay instead of multiple relays. Based on our discussion from today, redesign the experience so the following is possible: 

- Users can choose one or more relays to post a note to
- Users make that decision when posting 
- Users understand the default option is All relays

**Comment by Chardot** [comment]
I designed a [user flow for selecting one or multiple relays](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=7560-7372&t=v7fXqtePw7vJBCVq-1) to which a note will be posted, right from the editor:

![Image](https://github.com/user-attachments/assets/88deaf30-87dd-4746-b7b6-bf774bd746de)

It starts by consolidating the relay selector in the Post button:

![Image](https://github.com/user-attachments/assets/d37f6109-d4c3-4200-a7fd-d1729c8b921b)

Where the actionable area to open the relay selector (in green) is much larger than the dropdown itself, to prevent triggering ther Post action unintentionally:

![Image](https://github.com/user-attachments/assets/f02793c9-d88f-4f29-9f5d-8c5b17e31577)

By tapping on the dropdown for the first time, the relay selector displays all relays selected

![Image](https://github.com/user-attachments/assets/bc79f5d1-e856-4060-8cf4-dcfcc088eedb)

When the [All my relays] switch is pressed, all but Nos.social relays are disabled (since it's not possible to disable absolutely all relays):

![Image](https://github.com/user-attachments/assets/1e6722a0-31f8-4353-9220-754e87d81a96)

The label in the Post button is updated in real time with the number of relays that are selected:

![Image](https://github.com/user-attachments/assets/a2a7349b-6042-4b12-9d7f-fe07c0ecf048)

I hope this design reflects the scope of this task. Let me know if I can improve it.
