### ISSUE TITLE
[Media Display] Remove orange media link from notes

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1487]
Given that I am a user of Nos 
When I am viewing a note
Then I should NOT see the media url in the Note 
AND 
I should see the media 
or a missing / broken link option. 

For phase one users should not see separate media links for things that end in the following:
.png
.jpg
.jpeg
.mp4
.gif
.webp

Examples below: 

![IMG_0886701DB2C0-1](https://github.com/user-attachments/assets/237f28f3-32df-48a0-bd36-81012a8599e8)

![IMG_8877](https://github.com/user-attachments/assets/4be69126-fd64-4556-8a95-b56f310f9dba)

![IMG_8878](https://github.com/user-attachments/assets/08c583e8-6fcb-463c-9344-6a8c795d3464)

![IMG_8879](https://github.com/user-attachments/assets/852550cd-c010-42a3-a12c-df6c983a4806)

**Comment by mplorentz** [comment]
I brought this concern up during design review and I'm not sure if it was considered and dropped or was forgotten about. Apologies if this has already been considered.

We shipped code to do this in the past and people thought it was a bug, so we ended up reverting it. The position of a link in the note body is often significant and removing them makes some note contents nonsensical. I might not be so bad if we rendered media inline but because we render them at the very bottom of the note it can really mess some notes up.

I think in some cases we can safely remove the media URLs without causing these problems. But we need a more complex set of rules about when to do it. For instance, links appearing at the end of the note could clearly be hidden since the gallery is basically rendered in their place. Perhaps media links at the top of the note could be the same? Damus has rules like this last I checked.

For a quick example, open [this note](https://njump.me/note1z5xaj9l26rh9gjdh3cdcwt54kpfukv7qvvzwzp5z7s3medgfcu0qv0qt3f) in Nos and imagine how it would look with the notes removed. The "Full changelog:" text with no link would be confusing. And the "###Links" section at the bottom would be in the wrong place.

**Comment by setch-l** [comment]
Hi @mplorentz - This is a good catch in that this ticket is not explicit enough. When I say media links I mean links from nostr.build, nostrpic etc. 

As a first pass we should not display the links from the known media hosting servers on Nostr.

**Comment by joshuatbrown** [comment]
@setch-l we don't currently have a broken link view, so I created #1583.
