### ISSUE TITLE
[Design] Redesign the mentions experience

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1509]
The mentions experience in Nos today is limited to device search and display name, and is intrusive/disruptive from a UX perspective. See product brief for details. https://www.notion.so/nossocial/Mentions-82253f9de7d44747a042844cdfe1be07?pvs=4

Process
1. Document the current mentions experience in Nos
2. Review 1 Nostr and 2 external mentions experiences and document 
3. Share w/ product 
4. Create a sketched new mentions experience 
5. Share w/ product 
6. Design review
7. Create comps

**Comment by Chardot** [comment]
I started by documenting [Nos' mention user flow](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=8966-14620&t=WvjFtDo2BQREF87w-1).

![Image](https://github.com/user-attachments/assets/f8047279-c559-4f12-8571-05648bc40e92)

And then I did the same for:

- Ivory (Mastodon)
- Warpcast (Farcaster)
- Primal (Nostr)

The [I wireframed new mention user flows](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=8912-1187&t=WvjFtDo2BQREF87w-1) capturing the best of all the researched apps.

![Image](https://github.com/user-attachments/assets/d81b0775-4d61-4d18-9ac1-1207216ccea6)

I wireframed 3 cases:

- User mentions someone while replying to a note
- User mentions someone by their npub
- User fails to mention because no user is found

After presenting in Design review and iterating on them with Linda, [I produced visual designs](https://www.figma.com/design/s0qf4VmyQygydP8MIQazZc/Nos?node-id=8966-3461&t=WvjFtDo2BQREF87w-1) for mentioning users by display name and npub in both new notes and rep[lying to existing notes:

![Image](https://github.com/user-attachments/assets/74dfbcef-8293-4f7a-91fc-91e06d1e89a5)

I'm currently responding to feeedback before sending this to UAT.
