### ISSUE TITLE
[Media Display] Do a phase 1 release of the following display items

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#1538]
Remove the feature flag for the the following media display work: 
 
- All image related tickets including orientation, interaction, and carousel work
- All gif related tickets including play & interactions 

If you want to include NIP92 metadata and video orientation, you can. 

Create a new feature flag for the rest of the media display work.

**Comment by joshuatbrown** [comment]
@setch-l I'll plan to include everything we've done so far for the media display since we've gone through QA on almost all of it. 

This ticket is still in QA: https://github.com/planetary-social/nos/issues/1425
And this one is still in UAT: https://github.com/planetary-social/nos/issues/1488

But I'm confident in those and we can always change things in the event they don't pass QA. So we'll include everything for now and see how it goes.

**Comment by mplorentz** [comment]
@joshuatbrown can this be moved to UAT?
