### ISSUE TITLE
'Post' button obscured by long relay name

### ISSUE THREAD

**Issue by kiwipete** [planetary-social/nos#220]
When posting to a relay with a long name on a smaller screen device (iPhone8 in my case), the 'Post' button is hidden behind the relay name. 
![NOS_post](https://user-images.githubusercontent.com/2101002/229946623-a19dd3a5-8721-40cf-8a82-16c36fd729de.png)

**Comment by mplorentz** [comment]
Thanks for reporting this @kiwipete. I have noticed this layout is also broken at large text sizes.

**Comment by Chardot** [comment]
I updated the design of the relay selector so it displays a maximum of 14 characters (plus the ellipsis) in a smaller font size, ideally 1pt bigger than in the «Cancel» and «Post» buttons:

![Image](https://github.com/planetary-social/nos/assets/477835/bd63faf8-4695-4f70-892b-8b8a220de186)

I also redesigned the icon, and I packed them in [this .zip file](https://github.com/planetary-social/nos/files/11435111/Relay_selector.zip).

Let me know what you think, @mplorentz!

**Comment by mplorentz** [comment]
@Chardot I like the new design! I'm not sure that limiting the number of characters to 14 will be enough to keep it from overlapping the buttons at the really large font sizes. It also would be unfortunate to keep it so short for iPad and Mac users who have a lot more space to display the full domain name. 

Ideally we would be able to just set the margins on the control and let it fill the available space, but the system UINavigationBar isn't designed to work that way (which is why we have this issue in the first place).

I played with Apple's acessibility settings and they seem to have set a max font size for elements in the navigation bar. Maybe we should just do the same?
https://github.com/planetary-social/nos/assets/1165004/c5c2228b-1d5a-4541-9393-8c881a07dbcd

Then maybe I could just hard code a higher value for the Mac and iPad versions. So maybe in the iPhone it's 14 characters and on the iPad/Mac it's 28 or something. What do you think?

**Comment by mplorentz** [comment]
Yeah, we can pair and hash out the details when it's time to implement this. I'll move it into the backlog.
