### ISSUE TITLE
Feed pagination

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#223]
Currently we do very simple queries for the home feed, discover feed, profile view, and thread views and just constantly stream posts in from relays. This is creates several bad experiences:
- when you first open a feed it takes a few seconds to load new posts and we don't communicate this to the user with a loading indicator
- when new posts come in it causes the feed to jump and you can lose track of the note you are reading
- you can scroll to the bottom of a feed and it won't load more messages. 
- sometimes there are gaps of several hours or days in a feed that are never loaded
- we quickly hit our subscription limit with relays which prevents us from quickly loading author metadata, replies, and likes.

There are several features we need to get to the desired outcome, which is a feed that feels reliable - quickly shows you the latest data and allows you to browse it confidently.
- in the code we need to paginate the requests to load notes. This will let us quickly and efficiently fetch all the data we need.
- We need to show loading indicators at appropriate times
- We need to inform the user when new content has loaded (in Planetary we used the floating refresh button).

**Comment by Chardot** [comment]
In the following designs I'm covering 3 aspects:

1. Pulling down to fetch new notes
2. Showing that new notes are available
3. Scrolling down to trigger infinite scroll

I have two design proposals for these issues: one more simplistic (A) the other one more sophisticated (B).

A.1 Pulling down to fetch new notes

![Screenshot 2023-04-13 at 14 26 11](https://user-images.githubusercontent.com/477835/231759300-9c88ccd9-c103-4715-a2c7-edb69bb674a0.png)
 As the user pulls down from the top, a bar fades into view, centered in the padding that separates the first not from the bottom edge of the nav bar.

On release, the bar displays the following animation to show that it's fetching for new notes:

https://user-images.githubusercontent.com/477835/231759999-80bff5eb-3af1-4be9-8235-d6e26d14f8e5.mp4

A.2 Once the new notes have been loaded at the top of the feed, an indicator with the number of new notes is displayed right next to the Screen title.

As the user scrolls up to read the new notes, the number of unread notes decreases one by one:

![Screenshot 2023-04-13 at 14 26 23](https://user-images.githubusercontent.com/477835/231760634-452f7d7f-f52a-4b2e-9ea2-6af717810ec6.png)

The indicator could be actionable, so that from any point in the feed where the user is reading, tapping on it would take the user up in the feed to the first unread note.

A.3 The same animated bar is displayed when the user approaches the bottom of the feed. This could be triggered at 25% of the viewports height before the bottom border is reached to avoid a "bumping" sensation.

![Screenshot 2023-04-13 at 14 28 46](https://user-images.githubusercontent.com/477835/231761469-0064c79b-3cfd-46f0-809d-4003516b70b2.png)

B.1 An alternative design is having the bar integrated in the bottom border of the nav bar, where a slighly different animation shows that the app is looking for new notes:

![Screenshot 2023-04-13 at 14 26 50](https://user-images.githubusercontent.com/477835/231761900-a92f7b6c-be2a-421a-9ac5-506427c7eb62.png)

B.2 Instead of displaying a bubble with the number of new notes, the orange bar becomes full and, as the user scrolls up to read new notes, the orange par shrinks to indicate progress on reading the new notes.

The advantage that I see in this design, is that the bar could be used to communicate not only this but other actions in different contexts, and using different colors.

B.3

The same bar from A.3 is used to show the app is loading older notes into view:

![Screenshot 2023-04-13 at 14 28 46](https://user-images.githubusercontent.com/477835/231763604-996f8bbc-b097-4881-919d-4dc7b2a2eb7f.png)

@mplorentz What are your thoughts on these?

**Comment by mplorentz** [comment]
@Chardot I like both of these solutions, and both are similar amount of effort for me. Option A is a little more traditional, but the opportunities in Option B to use the lightweight "status line" to signal other things is also exciting. Did you have any other uses in mind?

Personally I would prefer that the unread indicators in both options were a more muted color. The orange is great for calls to action but I don't think we should be calling the user to read every post in their feed. This is unwanted stress for people (like me) who dip into the feed but don't have time to fully consume it.

**Comment by Chardot** [comment]
@mplorentz [Here's the link](https://share.getcloudapp.com/JrupypjO) to the animation.

I agree the indicators were too bright. What do you think of this monotone version?

![Screenshot 2023-04-13 at 17 02 08](https://user-images.githubusercontent.com/477835/231820412-0818215e-4017-48fe-8f0f-b456df8b5f05.png)

![Screenshot 2023-04-13 at 17 02 37](https://user-images.githubusercontent.com/477835/231820488-9c7954d2-addf-46e7-8c15-2500e8437aba.png)

I think the animaed border of the nav bar could be used to communicate that the app is posting a note with heavy content like video or sound, syncing with specific relays, displaying errors, etc.

**Comment by mplorentz** [comment]
@Chardot I am realizing that if we pick option B for the top bar I will still need to code up the custom loading indicator and pull-to-refresh gesture from option A for the bottom of the list. Given this fact maybe we should start with implementing option A first and see how we like it?

**Comment by Chardot** [comment]
Also thinking about the performance of the feed, I did this excercise of looking at multiple social media apps and «spinning the wheel» on each one's feed to find how many posts will users see after scrolling down as fast as they can in one push. I call this number a _page_.

So how many notes will we see on the feed after spinning the wheel?


Social app | Notes on a page
-- | --
Damus | 35
Planetary 2.0 | 33
Ivory | 25
Plebstr | 20
Pinterest | 19
Quora | 19
Twitter | 18
Bluesky | 15
Mastodon | 15
Tumblr | 14
Instagram | 11
MeWe | 11
SubStack | 10

The average is 20 posts, so loading 25 notes per page would keep us above the average. That is: in Nos, users will see more notes as they scroll, than in the average social network app.

So, in order to create an _infinite scrolling_ experience, we just need to inject a new page before the viewport reaches the bottom end of the current page. This way, users won't notice the transition between the current and the new page, as per the following image:

![Image](https://user-images.githubusercontent.com/477835/232868685-1ee07074-fb33-46aa-8a3e-2bdd6ae0500e.png)

My proposal is that as users keep scrolling down approaching the bottom of the second page, the 25 older notes from the first page are removed from the feed, effectively leaving 50 notes persisted on the feed at a given time:

![Image](https://user-images.githubusercontent.com/477835/232871737-b2bb4510-8d84-4360-afc4-7d59b65ea57b.png)

Scrolling up approaching the top end of the second page would trigger the removal of the 25 notes in the third page, and the injection of the 25 notes in the first page.

That would allow the app to concentrate most of the resources to render 50 notes with an excellent performance including features like dynamic font sizes, video autoplay, animated image galleries, gifs, stories, animations in polls, user follow suggestions, etc.

@mplorentz Is there a limit for how many notes can be present on the feed in the current version? What is your thinking around a proposal like this?

**Comment by Chardot** [comment]
> @Chardot I am realizing that if we pick option B for the top bar I will still need to code up the custom loading indicator and pull-to-refresh gesture from option A for the bottom of the list. Given this fact maybe we should start with implementing option A first and see how we like it?

Yes, let's go with A 🤙

**Comment by mplorentz** [comment]
The foundation for this is done, and it's implemented in the profile feed. I have created tickets to apply it to the other feeds:
- #767 
- #768 
- #783 
- #784 

I'm going to close this ticket and track the remaining work in those.
