### ISSUE TITLE
Show number of connected relays in the top right

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos#268]

**Comment by Chardot** [comment]
I'm proposing this button on the right end of the navigation bar:

![Screenshot 2023-04-27 at 18 17 14](https://user-images.githubusercontent.com/477835/234929487-9db83e44-2bcd-4553-830f-f2556e0b2ef8.png)

The «beams» are a good indicator of the way relays work, which we can also use to communicate if the relays are working well or not, or if the app is sufficiently connected to relays.

In the following images, we can see different states of the indicator:

![Screenshot 2023-04-27 at 18 20 12](https://user-images.githubusercontent.com/477835/234930256-37552a3b-665b-4fb6-81d6-9569ed73ba7e.png)

![Screenshot 2023-04-27 at 18 20 31](https://user-images.githubusercontent.com/477835/234930285-e706d829-fc34-43e5-8616-ab4ee14ca8cf.png)

This indicator is formed by 3 elements:

1. The relay count
2. The left beams
3. The right beams

![Screenshot 2023-04-27 at 18 35 53](https://user-images.githubusercontent.com/477835/234930708-05599142-a339-42f3-a549-484925850355.png)

It is designed this way so that the spacing can auto-correct when the number of relays change.

The indicator also adapts to both light and dark themes:

![Screenshot 2023-04-27 at 18 31 17](https://user-images.githubusercontent.com/477835/234930970-90e40386-e8a6-40ae-aa2a-d42308714b14.png)

![Screenshot 2023-04-27 at 18 28 19](https://user-images.githubusercontent.com/477835/234930992-b9124b11-222e-47a6-aea9-ba2279e340ca.png)

@boreq Let me know if you need guidance on how to implement this layout correctly.

**Comment by mplorentz** [comment]
@boreq we've shifted your priorities around and so unassigned you from this one.
