### ISSUE TITLE
Number of followers in your profile in Damus != number of followers in Nos

### ISSUE THREAD

**Issue by boreq** [planetary-social/nos#621]
Start investigating with @NotThatKindOfDrLiz's account.

I believe Damus shows 4 but Nos shows 2 for some reason.

**Comment by NotThatKindOfDrLiz** [comment]
![image](https://github.com/planetary-social/nos/assets/127434495/d390f6e9-d5bc-4fef-b544-fde67c91777a)

![image](https://github.com/planetary-social/nos/assets/127434495/626c55f6-2fd6-4e76-b42e-bf9102153ff4)

**Comment by mplorentz** [comment]
We are only counting the followers from the logged in user's two-hops social graph, not the global number of followers because you have to download the contact lists for all the Nostr users in the world in order to calculate that. Some apps use special servers to do this counting and probably that's what we should do in the future.

In the short term I changed the "Followed by" label to "Followers you know" to hint at the fact that we aren't counting all followers.

**Comment by mplorentz** [comment]
This is not really a bug anymore but we would like to show a global follower count in the future.
