### ISSUE TITLE
Users can get stuck in a loop when root notes can’t load 

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#801]
This was found in 0.1.2 (153). See this slack post for a video of the experience. https://planetary-app.slack.com/archives/CM4EPK324/p1704909201851959

**Comment by joshuatbrown** [comment]
@setch-l @rabble could you post steps to reproduce? When I tap a "Link to note", then tap the back button, everything seems to work as expected. In some cases, the linked note doesn't load, but going back is fine and it doesn't jump back into the thread for me. Am I missing a step or tapping the wrong place?

**Comment by mplorentz** [comment]
(I just fixed most of the cases of this in #703, so maybe that changes the priority of this issue. But it will always be possible that we just can't find a note, so this could still happen.)

**Comment by mplorentz** [comment]
@rabble is correct, when Linda taps the link it opens the correct note. We could prevent the app from pushing the same thread view, but then tapping the link will do nothing and users will think that part is broken. We could change how the quoted note is rendered to make it more obvious that the link inside is referencing the note at the root of the thread. We could:
- completely hide quoted notes from the thread view (easy but probably not the best UX)
- render a backlink that says "so and so quoted this note" as discussed in the thread @setch-l [mentioned](https://planetary-app.slack.com/archives/CM4EPK324/p1712405953621279)
- render the root note inside the quoted note card in place of the "link to note" text
- Make a new style of card that hides the "link to note" text and says "quoted" instead of "replied" at the top.

If we agree that the best path forward here is improving the rendering of quoted notes, maybe we close this ticket and use #840 to figure that out?

**Comment by setch-l** [comment]
@mplorentz - Can we implement the UI designs for quoted notes to solve this issue?

**Comment by mplorentz** [comment]
@setch-l I think so? I don't recall seeing those designs. Is #840 done?

**Comment by setch-l** [comment]
yeah - all this work is in tickets #940 - #944 - The designs are linked in the tickets. They are sitting in the no status column.

**Comment by mplorentz** [comment]
@setch-l I reviewed the designs and they look great! I think #944 is the one for displaying quoted notes, the others are about posting quoted notes. Would you like to close this ticket and prioritize #944?

**Comment by mplorentz** [comment]
(I guess some quick feedback on the designs - I still think a backlink would be more appropriate in the thread view. Because rendering the quoted note in the thread view will result in us showing the root note twice or more in the thread. Once at the top and again inline in every quoted note. But it will be less confusing than the current UI and the quoted notes will look great in the home feed)

**Comment by setch-l** [comment]
Based on a discussion with @mplorentz - We are going to close this ticket and implement quoted notes including in a thread. This means at the first release, when a user clicks on a quoted note, in the thread users will see both replies and quoted replies of the note. We'll see what sort of feedback we receive from this experience once its live. (The main concern being bad actors who use quoted notes to harass people).
