### ISSUE TITLE
Bug - Mentioning someone in a reply does not format the mention correctly

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#871]
Steps to reproduce:
1. Open nos
2. Write a reply to a note
3. Include in the reply an @npub mention of another user 
Issue: When the reply is published we display the full npub instead of the display name of the user. 

![Image](https://github.com/planetary-social/nos/assets/6765558/f3faa41c-3d3c-4a26-bc8e-c214f79609af)

**Comment by joshuatbrown** [comment]
@setch-l Do you have the link to this note or to another one that exhibits the problem?

**Comment by setch-l** [comment]
@joshuatbrown - sure here's an example from last week: note1ecph8rsnpmtavpspp3r309kxjf54s4rvqdf2ymxkupa5zl90tq0shjpz4e
https://njump.me/note1ecph8rsnpmtavpspp3r309kxjf54s4rvqdf2ymxkupa5zl90tq0shjpz4e

**Comment by joshuatbrown** [comment]
@setch-l thanks. Unfortunately that note isn't formatted quite right so we're not able to display it correctly. Here's the content of the note that I see:

> To be clear, this is me communicating the strategy that nostr:npub1ey39gym4zlppcsvquqhv0cujnsn6uwuu9z9f4sxkzp5vjy8gfa9sprdq23is developing coming out of our research talking to users, including folks on nostr, who have tried and left nostr, and those who haven’t yet tried it. More to come.

The issue here is that the npub is followed immediately by the word "is" -- the space between them is missing. We _might_ be able to determine where the npub is supposed to end and show the username even if there's no space, but I don't know if npubs are always the same length so I can't say for sure.

What we probably want to do -- if we're not already -- is ensure that there's a space after the username when the user is composing a note. We may already have a ticket for that.

**Comment by joshuatbrown** [comment]
Update: we do have a ticket for adding a space while composing: #535

**Comment by setch-l** [comment]
Great - This is a variation of #535. We'll close this one. @joshuatbrown - please focus on #535 and continue updating that ticket with any questions etc.
