### ISSUE TITLE
Update Readability of Dark theme

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#891]
Refer to this Miro board for examples of readability issues in Dark Mode. 
https://miro.com/app/board/uXjVNsfn4sI=/

Acceptance criteria
- Main screens of the nos app: Feed, Discover, Notifications, Profile all meet WC3 or 2 requirements for contrast 
- Sub screens - Thread view, edit profile, Settings meet WC3 or 2 standards for contrast and size of text - there's some very tiny text on threads and Edit Profile. 

Ideally the results of this work are in a form that enables the engineers to quickly update the classes in Swift.

**Comment by Chardot** [comment]
### Status update

Based on these results from the [contrast & legibility test in Miro](https://miro.com/app/board/uXjVNsfn4sI=/):

![Image](https://github.com/planetary-social/nos/assets/477835/14ca0bad-d924-43da-ad2e-ad0aa7d9a076)

I identified that the elements with compromised contrast and legibility are the ones displayed in Secondary color (currently #8A77B6) against the current note background gradient (which at its lightest point is #2A1D46).

### Improving Color Contrast

In order to measure the contrast ratio by the [WCAG 2.1 Standards](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum) I downloaded a desktop [app called Contraster](https://apps.apple.com/es/app/contraster/id6464116077?l=en-GB&mt=12), which lets the user pick two colors from the screen and shows the resulting value.

The current contrast ratio on Secondary text is 3.96:1:
![Image](https://github.com/planetary-social/nos/assets/477835/5150da4e-5631-47b0-99de-d2c0296cd6d1)

The [WCAG 2.1 website](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum) states that the minimum required contrast ratio for Large text is 4.5:1

So I went back to our [color palette](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5169%3A25565&mode=design&t=jFzoejcHnAXrRn4d-1) and changed the Secondary color and the note background gradient, which resulted in an improved contrast of 5.29:
![Image](https://github.com/planetary-social/nos/assets/477835/6a47ee1e-b012-4bc7-8642-ca5306bada6f)

These are the [new colors](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5169%3A25565&mode=design&t=F4RwL5zNciDOOb3W-1):
![Image](https://github.com/planetary-social/nos/assets/477835/05c465bf-16eb-48b1-b989-b8bd7c14b053)

And [this is the new background gradient](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5228%3A32180&mode=design&t=RC22QkIoJy4jcidh-1) for note and form cards:

![Image](https://github.com/planetary-social/nos/assets/477835/53061483-d903-4985-889b-2186311233a5)



### Improving Text Legibility

We use two different fontsin the app: [Clarity City](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5169%3A24521&mode=design&t=RC22QkIoJy4jcidh-1), for most titles and subheadings:

![Image](https://github.com/planetary-social/nos/assets/477835/ac948a40-e6e0-432b-8219-605a8a1b91c4)

and [SF Pro Text](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5228%3A31621&mode=design&t=RC22QkIoJy4jcidh-1), for body text in notes and form labels:

![Image](https://github.com/planetary-social/nos/assets/477835/62f4e312-6710-496c-9b4e-32ee444bf6dd)


The current build already uses a font-size that is compliant with [Apple's Dynamic Font Size](https://developer.apple.com/design/human-interface-guidelines/typography#iOS-iPadOS-Dynamic-Type-sizes) reference table, which defines that body text should be 17pt, with a leading (or line height) of 22pt.

This size is correct and will adapt to the dynamic type accessibility settings defined by the user for the entire system. However, there are 3 screens where we had some elements with really small font sizes: Edit Profile, Settings and Thread.

I updated the font sizes on these screens according to the Apple recommended sizes and added callouts on every element detailing their name, [dynamic type class name], font, weight, size, leading (or line height) and their color setting, as follows:

![Image](https://github.com/planetary-social/nos/assets/477835/3e6f8abf-23ad-4ac6-80c1-9859d5749188)

So [here's Edit Profile](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5228%3A31642&mode=design&t=RC22QkIoJy4jcidh-1):

![Image](https://github.com/planetary-social/nos/assets/477835/9295d5fc-66b6-4b97-a6bf-1d5152306a92)

Here's [Settings](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5228%3A31758&mode=design&t=RC22QkIoJy4jcidh-1):

![Image](https://github.com/planetary-social/nos/assets/477835/7b3d17ea-6ce8-4445-a814-5192c47c603a)

And [this is Threads](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5228%3A31858&mode=design&t=RC22QkIoJy4jcidh-1):

![Image](https://github.com/planetary-social/nos/assets/477835/dcf4fb1a-d6f2-41c3-ac4c-823cf8664cfd)


### [The Figma File](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5169-23469&mode=design)

With this work my intention was not only to address the specific problems with color contrast and text legibility, but most importantly to define a better standard for Designer > Engineer handout.

Up until now designs have been delivered in an inconsistent and disorganized way which slowed down engineers by showing them too much noise and not exposing the right information clearly, and also slowed down my design workflow because I often lost the main goal of the task at hand by not seeing clearly where all the elements and components in the design were.

So for this taks I improved the presentation layout of [the design](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5169-23469&mode=design):

![Image](https://github.com/planetary-social/nos/assets/477835/b41974c3-e5a5-4fcc-8a08-89ca44d13c4f)

I split every aspect of the design solution problem into its own frame, which allows me to get a specific link to that section and point to them from Github Issues and Slack.

I also added a green dot 🟢 with a [DEV READY] tag in front of the name to make it clear that these designs are the source of truth of what is to be implemented by engineers:

![Image](https://github.com/planetary-social/nos/assets/477835/a8ccd97d-a9db-46da-9feb-38334f78ee3a)

With this, I hope everyone finds design deilivery to be more simple and useful, and I encourage engineers @martindsq @mplorentz @rabble and @joshuatbrown to give me feedback on how I can continue improving this, from this comment on Github to the way I'm presenting and linking to the designs on Figma, etc.

**Comment by Chardot** [comment]
## Form of Presentation

#### Request
> Ideally the results of this work are in a form that enables the engineers to quickly update the classes in Swift.

#### Proposal

[Link to Figma File](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5169-23469&mode=design)

With this work my intention was not only to address the specific problems with color contrast and text legibility, but most importantly to define a better standard for Designer > Engineer handout.

Up until now designs have been delivered in an inconsistent and disorganized way which slowed down engineers by showing them too much noise and not exposing the right information clearly, and also slowed down my design workflow because I often lost the main goal of the task at hand by not seeing clearly where all the elements and components in the design were.

So for this taks I improved the presentation layout of [the design](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=5169-23469&mode=design):

![Image](https://github.com/planetary-social/nos/assets/477835/b41974c3-e5a5-4fcc-8a08-89ca44d13c4f)

I split every aspect of the design solution problem into its own frame, which allows me to get a specific link to that section and point to them from Github Issues and Slack.

I also added a green dot 🟢 with a [DEV READY] tag in front of the name to make it clear that these designs are the source of truth of what is to be implemented by engineers:

![Image](https://github.com/planetary-social/nos/assets/477835/a8ccd97d-a9db-46da-9feb-38334f78ee3a)

#### Request for Feedback

With this, I hope everyone finds design deilivery to be more simple and useful, and I encourage engineers @martindsq @mplorentz @rabble and @joshuatbrown to give me feedback on how I can continue improving this, from this comment on Github to the way I'm presenting and linking to the designs on Figma, etc.

**Comment by mplorentz** [comment]
Thanks @Chardot. I like the frames for organization, and I really like the titles inside each one. I think that will really help with searching for specific designs which has always been hard for me in Figma (usually I have a direct link to them, but when I don't this is useful). 

Personally I don't find the font information in the callouts necessary, because I can get the same info from the sidebar (and it will never be incorrect there) but the color information is nice as at least in the past it has been hard to figure out the semantic color name (like "secondary text") from the hex code. I think the callouts could also be very useful for notes about animations, interactions, or whatever.

**Comment by martindsq** [comment]
Impressive work @Chardot. Thanks for changing the bottom gradient of the note cards to have more contrast with the app background, I cannot wait to see those changes implemented! One thing though, did you evaluate about doing the same with the bottom toolbar to address the note I left in Miro?

I like the DEV READY label very much, and using color names on top of hex codes as well. Both are good ideas! Regarding the callouts with text/font information, I agree that's too much work for you and we don't gain much from it taking into account we can just see the details in the sidebar. But, maybe, you could consider just specifying the dynamic class names in the callout and that's it, because sometimes the text size is between two and I have to choose either a class that is smaller or another that is larger, and I think that will force you to think text size in terms of dynamic class instead of points.

Again, good work there!

**Comment by joshuatbrown** [comment]
@Chardot 100% agreed with @mplorentz -- I don't find the font info in callouts necessary, but I do like having semantic colors and notes for animations and interactions would be useful in those in the future. Agreed with @martindsq as well -- the Dev Ready label is great, and having the dynamic class names might be nice.
