### ISSUE TITLE
Nostr names,  notes, profile links, and npubs not detected in profiles

### ISSUE THREAD

**Issue by rabble** [planetary-social/nos#923]
We need to make the profile text go through the same rendering and link embedding process we do for note cards. 

![IMG_0442](https://github.com/planetary-social/nos/assets/76/04b54bcb-cef7-45ba-9180-b7aa5ae034d6)

**Comment by martindsq** [comment]
Thanks @rabble from pointing it out. It's not a regression because that was never done, but I'm fixing the parsing because the current quality is not enough. Also, I'm fixing the fonts and spacings because I see the values there are not correct, I'll be coordinating with Sebastian to fine-tune the text style of the bio.

**Comment by setch-l** [comment]
@martindsq - I don't think we provided explicit acceptance criteria for how this should work. My expectation is that the following would be possible when this work is completed: 
In a profile I can:
- Click on an npub and be taken to another profile if the npub is diff from the current profile 
- click on a NIP05 and be taken to another profile if the NIP05 is different from the current profile 
- The full NIP05 is recognizable in the profile. 



![Image](https://github.com/planetary-social/nos/assets/6765558/a1662166-7a8f-4294-877d-6a12252b1628)

**Comment by martindsq** [comment]
Let's break this down to:

When displaying the bio of the first profile (npub: npub1kmsnnxw6p8vlk2l2dh0443jkj0txl7jrww8qpx4vd428he0a8jqqy6tjep) we should:

- recognize the nip05 there ryanzyro@getalby.com even if it is prepended with @ (e. g. @ryanzyro@getalby.com)
- recognize the npub there npub1rx9knlwmqqmlhw3x6mfe0aglpvg44jrq0pf9zvkareuwq2rktx4qrtejy7

When displaying the bio of the second profile (npub: npub1ey39gym4zlppcsvquqhv0cujnsn6uwuu9z9f4sxkzp5vjy8gfa9sprdq23):

- recognize the nip05 there linda@nos.social
- recognize the npub there npub1ey39gym4zlppcsvquqhv0cujnsn6uwuu9z9f4sxkzp5vjy8gfa9sprdq23

None of these are proper nostr mentions (they aren't prepended with `nostr:`), or they are seldom prepended with a `@` as if they were usernames, but we want to parse them anyway.

**Comment by martindsq** [comment]
PS: this is not something we were just doing when rendering notes but not in the bios. It is an issue we could have in both places but I think it is most commonly seen in bios because users don't have the note editor that links profiles when editing their bio, they just have a simple text field there.
