### ISSUE TITLE
[BUG] NIP05 is blue link in mac / ipad app on profile & opens mail client

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#932]
Steps to reproduce
1. Open nos app
2. Navigate to a profile page with a nos.social nip05
Issue the NIP05 is blue & does not match styling in the app
Clicking on it opens the mail client, not a web browser to njump. 

![Image](https://github.com/planetary-social/nos/assets/6765558/ea5ec9f5-de03-4a07-bc66-fa7291088771)
![Image](https://github.com/planetary-social/nos/assets/6765558/35a18ada-4c77-4605-b97d-2d0646c493a6)

**Comment by joshuatbrown** [comment]
@setch-l Agreed that it should not be a link and not open the Mail app. I'm not sure it should go anywhere; it seems like that would be unexpected, especially since clicking/tapping the top of the screen scrolls to the top. I suggest we remove the link entirely and just have it be plain, unclickable text.
