### ISSUE TITLE
Users who generate new keys auto follow nos.social & Tagr-bot accounts

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#936]
Why: 
1. We want new users to see the weekly listicles and other content reshares from the creator / journalist residency programs. 
2. In the future, with Dm's we can welcome folks to Nos. (Let's not turn on auto - welcomes yet bc people may unsubscribe.) 

Given that I am a new user to Nos and Tagr 
When I generate a new key
I should automatically follow the nos.social and Tagr-bot accounts in Nostr.

**Comment by mplorentz** [comment]
Just want to note a perhaps unintended consequence of this: the home feed will show only Nos content until the user starts following people. We will land them on the Discover tab so hopefully they will follow people quickly. But I've seen a lot of people start tapping the tabs immediately after finishing onboarding, so those folks will see a Home screen full of basically just release notes, instead of a message telling them to go follow people on the Discover tab.

Not saying we shouldn't do this, but maybe we consider prioritizing more work in this direction. Like the special welcome cards we show in Planetary, or a welcome bot that sends DMs, or publishing more diverse content from the Nos account.
