### ISSUE TITLE
Mention posting / display broken 

### ISSUE THREAD

**Issue by rabble** [planetary-social/nos#962]
When a user mentions someone in their post it generates a link in a way which doesn’t display correctly in nos, it’s mangled markdown, and it’s getting the mention name all wrong when displayed in Damus. 

[IMG_0577](https://github.com/planetary-social/nos/assets/76/e992265c-a664-4f08-a2e8-7ed880dc3a15)
[IMG_0576](https://github.com/planetary-social/nos/assets/76/002540af-d44b-4f40-a6eb-5ae090a8b201)

To reproduce:
Open app
Find note
Write reply
Mention someone 
View reply on nos and other apps. 

Note source

  "sig" : "a8a02e610a4a277ae488d66e37e1f22a01c37e00270b377302431d3e19ba13f9957008bb9f16ba6b2b96d5d08070adc2836e07d4d6fe72658ab64fa30d3e4bb7",
  "pubkey" : "76c71aae3a491f1d9eec47cba17e229cda4113a0bbb6e6ae1776d7643e29cafa",
  "tags" : [
    [
      "p",
      "0f22c06eac1002684efcc68f568540e8342d1609d508bcd4312c038e6194f8b6"
    ],
    [
      "p",
      "8c430bdaadc1a202e4dd11c86c82546bb108d755e374b7918181f533b94e312e"
    ],
    [
      "e",
      "a9788ca56a90bb5b856e89f16f5f3b0da93c28ea625e845c9925a41377152a13",
      "",
      "root"
    ],
    [
      "e",
      "3d9503a2d4ad024749b138c041e99934474e2822e2a1c697792dab5b24acc285",
      "",
      "reply"
    ]
  ],
  "kind" : 1,
  "created_at" : 1710580164,
  "id" : "a3eb8ecb7a5336e621c6e8769b6bec2dd69f186fa9017be19803a7085a2bed2e",
  "content" : "Yep. Something like that. I, of course could implement it in nostr:npub1pu3vqm4vzqpxsnhuc684dp2qaq6z69sf65yte4p39spcucv5lzmqswtfch but haven’t yet. "
}

**Comment by setch-l** [comment]
Some additional information: 
I tried to mention Meredith Whittaker a Mastodon user. I could not find her in the mentions search. So I @ her npub instead. In the preview the npub was linked. In the app it displays only as text. Here's a link to the post: 
https://njump.me/note1qgk7s9clnxuzspm7t3phkmjxggftt46v06pkp3px0upg9knzmygs0zpl4z

Npub for the post: note1qgk7s9clnxuzspm7t3phkmjxggftt46v06pkp3px0upg9knzmygs0zpl4z

The minimu acceptance criteria is that if the editor shows a linked npub than the posted note should at a bare minimum show the linked npub. Bonus if it translates to the display name for the user.

**Comment by martindsq** [comment]
**Describe the bug**
The app fails to properly display mentions to users that contain what could be a valid url as the name. For example, nos.social. Right now, nos.social account is just named nos, but at the time @rabble posted this issue, it was nos.social.

**To Reproduce**
Steps to reproduce the behavior:
1. Rename yourself to a valid url, like me.test
2. Open the Note composer
3. Type a note tagging yourself, like "Hi @me.test"
4. The app displays a note with mangled markdown instead

Alternatively, I created an account like that to test this:

1. Open the Discover screen
2. Search for `npub1merzyaqchrndz7wy73y5tdu9slskav6jpz2qq7pljyy9j6hxmdnq2dr4qy` in the search bar
3. Watch the mangled markdown in the posts I created tagging myself.

**Expected behavior**
It should display with "hello @me.test" and "hi @me.test"

**Screenshots or Video**
![IMG_606C2197D628-1](https://github.com/planetary-social/nos/assets/1703242/6689cd7a-7bae-4c67-8e8b-b4172964ec78)


**Technical info (please complete the following information):**
 - OS: iOS
 - App Version: 0.1.11 (241)
 - Environment: Staging
