### ISSUE TITLE
[Moderation Hot fixes] Update the account reporting screens

### ISSUE THREAD

**Issue by setch-l** [planetary-social/nos#991]
Update the menu for reporting an account to the following options

Harrasment - Harmful and unwanted replies or mentions.
Spam 
NSFW - Nudity, porn, or violent content not appropriate for work
Illegal - Copyright violations, CSAM or other illegal content
Other - Issue not included in these options.

**Comment by setch-l** [comment]
@Chardot - I don't see screens for Account reporting which is different than Content reporting. Perhaps you grabbed the wrong ticket?? We can also talk about this on Monday.

**Comment by Chardot** [comment]
Here's the [current user reporting flow](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=6021%3A5039&mode=design&t=924vsspzjnWzKc2a-1):
![Screenshot 2024-04-17 at 19 21 30](https://github.com/planetary-social/nos/assets/477835/31d33cdb-8e03-4341-a2a1-679737070558)

1. This is a [design hot fix](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=6021%3A6863&mode=design&t=924vsspzjnWzKc2a-1) making use of the current options menu, just as proposed on [980 - Content Reporting](https://github.com/planetary-social/nos/issues/980):
![Screenshot 2024-04-17 at 19 21 40](https://github.com/planetary-social/nos/assets/477835/1d87f912-ba90-4ee3-bd14-133909227dad)

2. And [here's a proposal for an improved flagging UX](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=6021%3A5765&mode=design&t=924vsspzjnWzKc2a-1) using a custom sheet component:
![Screenshot 2024-04-17 at 19 21 48](https://github.com/planetary-social/nos/assets/477835/cb8bd17c-642b-4671-b370-d1665eaf77b2)

Note that when producing the design for [980](https://github.com/planetary-social/nos/issues/980), the copy for each option was improved and @setch-l opted to use the term "flag" instead of "report", and that's exactly what I reproduced here.

**Comment by setch-l** [comment]
@Chardot - You will need to update the hot fix designs based on what we learned today. Can you take care of that today or first thing tomorrow morning so I can write stories?

**Comment by Chardot** [comment]
> @Chardot - You will need to update the hot fix designs based on what we learned today. Can you take care of that today or first thing tomorrow morning so I can write stories?

@setch-l After discussing with @dcadenas and @joshuatbrown we came to the conclusion that the action sheet menu cannot be implemented as it was designed, [so here is the updated the Figma designs to reflect its limitations](https://www.figma.com/file/s0qf4VmyQygydP8MIQazZc/Nos?type=design&node-id=6068%3A4684&mode=design&t=HEHtN12NGQmL0d1s-1):

![Screenshot 2024-04-18 at 23 36 27](https://github.com/planetary-social/nos/assets/477835/336713e6-fef2-4832-bf9e-5c04266b1e6d)
